before_script:
  - docker info
  - printenv

stages:
  - test
  - pylint
  - build
  - deploy

# Run django unit tests
test_backend:
  stage: test
  tags:
    - arm64
  before_script:
    - pip3 install pipenv
    - export PATH=$PATH:/home/gitlab-runner/.local/bin
    - pipenv install
  script:
    - cd backend/
    - pipenv run coverage run --source='.' --omit='*manage.py,*wsgi.py,*asgi.py,*/tests.py,*unit_test_helpers.py,*/migrations/*.py' manage.py test
    - pipenv run coverage report -m --precision=1
  coverage: '/TOTAL.*\s+(\d+\.\d+\%)$/'
  only:
    - master

# Run react unit tests
test_frontend:
  stage: test
  tags:
    - arm64
  before_script:
    - npm install -D
  script:
    - npm test -- --coverage
  coverage: '/All files.*\|.*\|.*\|.*\|.*\s+(\d+\.\d+)/'
  only:
    - master

# Update pylint badge
pylint:
  stage: test
  tags:
    - arm64
  before_script:
    - pip3 install pipenv
    - export PATH=$PATH:/home/gitlab-runner/.local/bin
    - pipenv install --dev
  script:
    - mkdir ./pylint
    - pipenv run pylint --output-format=text backend/plant_tracker/ | tee ./pylint/pylint.log || pipenv run pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - pipenv run anybadge --label=pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 3=red 5=orange 7=yellow 9=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/
  only:
    - master

# Build new container, increment most-recent tag
build:
  stage: build
  tags:
    - arm64
  script:
    - 'export IMAGE_NAME="plant-tracker"'
    - 'export LAST_TAG=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^${IMAGE_NAME}:[0-9]*\.[0-9]*$" | sort --version-sort | tail -n 1 | cut -d\: -f 2)'
    - "export NEW_TAG=$(echo $LAST_TAG | awk -F. '{$NF = $NF + 1;} 1' OFS=.)"
    - 'docker build --platform linux/arm64 -t $IMAGE_NAME:$NEW_TAG . -f frontend/docker/Dockerfile'
  only:
    - master

# Deploy most-recent container
deploy:
  stage: deploy
  tags:
    - arm64
  script:
    - 'export IMAGE_NAME="plant-tracker"'
    - 'export LAST_TAG=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^${IMAGE_NAME}:[0-9]*\.[0-9]*$" | sort --version-sort | tail -n 1 | cut -d\: -f 2)'
    - 'sed -i "s|$IMAGE_NAME:[0-9]*\.[0-9]*|$IMAGE_NAME:$LAST_TAG|g" /home/pi/docker/docker-compose.yaml'
    - 'docker compose -f /home/pi/docker/docker-compose.yaml up -d'
  only:
    - master
