services:
  plant-tracker:
    image: plant-tracker
    container_name: plant-tracker
    hostname: plant-tracker
    environment:
      # Comma-seperated list, access on all others will be blocked
      # Defaults to * if omitted (not recommended)
      - ALLOWED_HOSTS=plants.lan,localhost
      # Domain for QR code URLS, use one of the ALLOWED_HOSTS
      - URL_PREFIX=plants.lan
      # Postgres database password (must match container below)
      - DATABASE_PASSWORD=supersecretpassword
      # Optional: All postgres settings can be overridden with env vars
      # - DATABASE_NAME=
      # - DATABASE_USER=
      # - DATABASE_HOST=
      # - DATABASE_PORT=
      # Optional: Disables user accounts and authentication if True
      - SINGLE_USER_MODE=False
      # Optional: Persistent key between sessions
      # If blank a new key will be generated each time
      - SECRET_KEY="xxxxxxxxxxxxxxxxxxxxxx"
      # Optional: Admin interface credentials, will be created if
      # username and password are set (email is optional)
      - DJANGO_SUPERUSER_USERNAME=myusername
      - DJANGO_SUPERUSER_PASSWORD=mypassword
      # - DJANGO_SUPERUSER_EMAIL=
    volumes:
      # Persistent storage between sessions
      - plant-tracker-data:/mnt/backend/data/
    ports:
      - 8456:8456
    restart: unless-stopped

  plant-tracker-db:
    image: postgres:17.5
    container_name: plant-tracker-db
    # shared memory limit
    shm_size: 128mb
    environment:
      POSTGRES_DB: plant_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - plant-tracker-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  plant-tracker-data:
  plant-tracker-database:
