version: "3.5"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/pi/docker/nginx:/etc/nginx/certs
    restart: unless-stopped
    networks:
      - reverse_proxy

  plant-tracker:
    image: plant-tracker:latest
    container_name: plant-tracker
    hostname: plant-tracker
    environment:
      # Reverse proxy domain name
      - VIRTUAL_HOST=plants.lan
      # Comma-seperated list, access on all others will be blocked
      # Defaults to * if omitted (not recommended)
      - ALLOWED_HOSTS=plants.lan,localhost
      # Domain for QR code URLS, use one of the ALLOWED_HOSTS
      - URL_PREFIX=plants.lan
      # Optional: Persistent key between sessions
      # If blank a new key will be generated each time
      - SECRET_KEY="xxxxxxxxxxxxxxxxxxxxxx"
    ports:
      - 8456:8456
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    name: reverse_proxy
    driver: bridge
