# Generated by Django 5.0.2 on 2024-02-11 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repotevent",
            name="new_pot_size",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(36),
                ],
            ),
        ),
        migrations.AddField(
            model_name="repotevent",
            name="old_pot_size",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(36),
                ],
            ),
        ),
    ]
