# Generated by Django 5.0.1 on 2024-02-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_tracker", "0002_tray_plant_tray"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fertilizeevent",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="waterevent",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
