# Generated by Django 5.0.2 on 2024-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_tracker", "0002_repotevent_new_pot_size_repotevent_old_pot_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="tray",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
