# Generated by Django 5.0.3 on 2024-03-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_tracker", "0004_plant_created_tray_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="images")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_tracker.plant",
                    ),
                ),
            ],
        ),
    ]
