# Generated by Django 5.0.3 on 2024-04-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_tracker", "0007_add_missing_photo_thumbnails"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="default_photo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="plant_tracker.photo",
            ),
        ),
    ]
