# Generated by Django 5.0.3 on 2024-05-09 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0008_plant_default_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=2000, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_tracker.plant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
