# Generated by Django 5.0.3 on 2024-05-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0010_fix_photo_created_timestamps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tray',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='tray',
            new_name='group',
        ),
    ]
