# Generated by Django 5.0.6 on 2024-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0011_rename_tray_group_rename_tray_plant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
