# Generated by Django 5.0.6 on 2024-06-03 07:14

from django.db import migrations
from django.conf import settings


def get_thumbnail(plant):
    '''Takes Plant entry and returns thumbnail URL shown on frontend PlantCard.
    Returns URL of user-configured default_photo if set.
    Returns URL of most-recent photo if default not set.
    Returns None if plant has not photos.
    '''
    if plant.default_photo:
        return f'{settings.MEDIA_URL}{plant.default_photo.thumbnail.name}'
    try:
        # Most recent photo
        return f"{settings.MEDIA_URL}{plant.photo_set.all().order_by('-created')[0].thumbnail.name}"
    except IndexError:
        return None


def add_missing_thumbnail_urls(apps, schema_editor):
    '''Iterate Plant model and call update_thumbnail_url method to populate the
    new thumbnail_url field for existing entries.
    '''
    Plant = apps.get_model('plant_tracker', 'Plant')
    for plant in Plant.objects.all():
        plant.thumbnail_url = get_thumbnail(plant)
        plant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0012_plant_thumbnail_url'),
    ]

    operations = [
        migrations.RunPython(add_missing_thumbnail_urls),
    ]
