# Generated by Django 5.0.6 on 2024-06-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0013_add_missing_thumbnail_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteevent',
            name='text',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
