# Generated by Django 5.0.6 on 2024-09-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0014_alter_noteevent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
