# Generated by Django 5.1.6 on 2025-04-06 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0015_group_archived_plant_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_tracker.group'),
        ),
    ]
