# Generated by Django 5.2 on 2025-04-15 23:00

from django.db import migrations
from django.conf import settings


def set_default_user_email_address(apps, schema_editor):
    '''Sets a placeholder email address for the default user so the docker
    DJANGO_SUPERUSER_EMAIL env var can remain optional (if the default user has
    no email and the DJANGO_SUPERUSER_EMAIL env var is not set then the unique
    constraint will fail when docker entrypoint creates the super user).
    '''
    User = apps.get_model(settings.AUTH_USER_MODEL)
    default_user = User.objects.get(username=settings.DEFAULT_USERNAME)
    default_user.email = 'placeholder@joshmedeiros.dev'
    default_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0019_alter_group_user_alter_plant_user'),
    ]

    operations = [
        migrations.RunPython(set_default_user_email_address)
    ]
