# Generated by Django 5.2 on 2025-04-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0020_set_default_user_email'),
    ]

    operations = [
        # Rename the created field to timestamp (consistent with event and note
        # models which store the event/notes timestamp in the timestamp field)
        migrations.RenameField(
            model_name="photo",
            old_name="created",
            new_name="timestamp",
        ),
        # Rename the uploaded field to created (consistent with Plant and Group
        # models which both have auto_now_add DateTimeFields called created)
        migrations.RenameField(
            model_name="photo",
            old_name="uploaded",
            new_name="created",
        ),
    ]
