# Generated by Django 5.2 on 2025-05-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0021_rename_inconsistent_photo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews'),
        ),
    ]
