# Generated by Django 5.2.1 on 2025-06-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0023_replace_thumbnails_add_previews'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fertilizeevent',
            unique_together={('plant', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='noteevent',
            unique_together={('plant', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='pruneevent',
            unique_together={('plant', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='repotevent',
            unique_together={('plant', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='waterevent',
            unique_together={('plant', 'timestamp')},
        ),
    ]
