# Generated by Django 5.2.1 on 2025-06-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0024_alter_fertilizeevent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
