# Generated by Django 5.2.1 on 2025-06-10 00:46

from django.db import migrations
from django.conf import settings


def get_preview(plant):
    '''Takes Plant entry and returns preview URL shown on confirm_new_qr_code page.
    Returns URL of user-configured default_photo if set.
    Returns URL of most-recent photo if default not set.
    Returns None if plant has no photos.
    '''
    if plant.default_photo:
        return f'{settings.MEDIA_URL}{plant.default_photo.preview.name}'
    try:
        # Most recent photo
        return f"{settings.MEDIA_URL}{plant.photo_set.all().order_by('-created')[0].preview.name}"
    except IndexError:
        return None


def add_missing_preview_urls(apps, schema_editor):
    '''Iterate Plant model and populate the new preview_url field for existing
    entries.
    '''
    Plant = apps.get_model('plant_tracker', 'Plant')
    for plant in Plant.objects.all():
        plant.preview_url = get_preview(plant)
        plant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0025_plant_preview_url'),
    ]

    operations = [
        migrations.RunPython(add_missing_preview_urls),
    ]
