# Generated by Django 5.2.1 on 2025-06-10 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0026_add_missing_preview_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='divided_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_tracker.plant'),
        ),
        migrations.CreateModel(
            name='DivisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_tracker.plant')),
            ],
            options={
                'unique_together': {('plant', 'timestamp')},
            },
        ),
    ]
