# Generated by Django 5.2.1 on 2025-06-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0027_plant_divided_from_divisionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='divided_from_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plants', to='plant_tracker.divisionevent'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='divided_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='plant_tracker.plant'),
        ),
    ]
