# Generated by Django 5.2.1 on 2025-06-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0028_plant_divided_from_event_alter_plant_divided_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='preview_url',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='thumbnail_url',
        ),
    ]
