# Generated by Django 5.2.3 on 2025-06-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0029_remove_plant_preview_url_remove_plant_thumbnail_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertilizeevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='pruneevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='repotevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='waterevent',
            options={'ordering': ['-timestamp']},
        ),
    ]
