# Generated by Django 5.2.3 on 2025-06-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0030_alter_fertilizeevent_options_and_more'),
    ]

    operations = [
        # Add constraint to ensure Plant.default_photo (OneToOneField) points to
        # a Photo instance with a ForeignKey to the same Plant (prevent setting
        # photo of a different plant as default_photo)
        migrations.RunSQL(
            sql="""
            ALTER TABLE plant_tracker_photo
            ADD CONSTRAINT photo_plant_id_id_unique UNIQUE (plant_id, id);

            ALTER TABLE plant_tracker_plant
            ADD CONSTRAINT plant_default_photo_fk
            FOREIGN KEY (id, default_photo_id)
            REFERENCES plant_tracker_photo (plant_id, id)
            DEFERRABLE INITIALLY IMMEDIATE;
            """,
            reverse_sql="""
            ALTER TABLE plant_tracker_plant
            DROP CONSTRAINT plant_default_photo_fk;

            ALTER TABLE plant_tracker_photo
            DROP CONSTRAINT photo_plant_id_id_unique;
            """,
        )
    ]
