# Generated by Django 5.2.3 on 2025-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0031_default_photo_matches_plant_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
