# Generated by Django 5.2.3 on 2025-07-01 06:35

from django.db import migrations


def load_existing_uuids(apps, _schema_editor):
    '''Populate the UUID model with all existing Plant and Group UUIDs'''
    Plant = apps.get_model('plant_tracker', 'Plant')
    Group = apps.get_model('plant_tracker', 'Group')
    UUID = apps.get_model('plant_tracker', 'UUID')

    uuids = (
        list(Plant.objects.values_list('uuid', flat=True)) +
        list(Group.objects.values_list('uuid', flat=True))
    )
    UUID.objects.bulk_create([UUID(uuid=u) for u in uuids])


class Migration(migrations.Migration):
    dependencies = [('plant_tracker', '0032_uuid')]
    operations = [
        migrations.RunPython(
            load_existing_uuids,
            reverse_code=migrations.RunPython.noop
        )
    ]
