# Generated by Django 5.2.4 on 2025-07-27 18:23

import plant_tracker.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0034_enforce_unique_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=plant_tracker.models.photo.public_storage, upload_to='thumbnails'),
        ),
    ]
