# Generated by Django 5.2.4 on 2025-07-27 19:49

import plant_tracker.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0035_alter_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=plant_tracker.models.photo.user_image_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=plant_tracker.models.photo.user_preview_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=plant_tracker.models.photo.user_thumb_path),
        ),
    ]
