# Generated by Django 5.2.6 on 2025-11-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0036_useremailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
