# Generated by Django 5.2.6 on 2025-11-05 07:02

from django.db import migrations


def set_pending_false(apps, schema_editor):
    '''Set pending attribute to False for all existing Photos.'''
    Photo = apps.get_model('plant_tracker', 'Photo')
    Photo.objects.all().update(pending=False)


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0037_photo_pending'),
    ]

    operations = [
        migrations.RunPython(set_pending_false, migrations.RunPython.noop),
    ]
