# Generated by Django 5.2.8 on 2025-11-15 04:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0038_populate_existing_photo_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsChangedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('name_before', models.CharField(blank=True, max_length=50, null=True)),
                ('name_after', models.CharField(blank=True, max_length=50, null=True)),
                ('species_before', models.CharField(blank=True, max_length=50, null=True)),
                ('species_after', models.CharField(blank=True, max_length=50, null=True)),
                ('description_before', models.CharField(blank=True, max_length=500, null=True)),
                ('description_after', models.CharField(blank=True, max_length=500, null=True)),
                ('pot_size_before', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ('pot_size_after', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_tracker.plant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('plant', 'timestamp')},
            },
        ),
    ]
