# Generated by Django 5.2.8 on 2025-11-17 05:56

from django.db import migrations


def create_details_changed_event_for_each_repot_event(apps, schema_editor):
    '''Creates DetailsChangedEvents with the same timestamp, old_pot_size, and
    new_pot_size of each existing RepotEvent where pot size changed.
    '''
    RepotEvent = apps.get_model('plant_tracker', 'RepotEvent')
    DetailsChangedEvent = apps.get_model('plant_tracker', 'DetailsChangedEvent')
    for repot_event in RepotEvent.objects.all():
        if repot_event.old_pot_size != repot_event.new_pot_size:
            DetailsChangedEvent.objects.create(
                plant=repot_event.plant,
                timestamp=repot_event.timestamp,
                pot_size_before=repot_event.old_pot_size,
                pot_size_after=repot_event.new_pot_size,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0039_detailschangedevent'),
    ]

    operations = [
        migrations.RunPython(
            create_details_changed_event_for_each_repot_event,
            migrations.RunPython.noop
        ),
    ]
