# Generated by Django 5.2.8 on 2025-11-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0040_create_details_changed_event_for_each_repot_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repotevent',
            name='new_pot_size',
        ),
        migrations.RemoveField(
            model_name='repotevent',
            name='old_pot_size',
        ),
    ]
