# Generated by Django 5.2.8 on 2025-11-18 00:37

import plant_tracker.models.pot_size_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0041_remove_repotevent_new_pot_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailschangedevent',
            name='pot_size_after',
            field=plant_tracker.models.pot_size_field.PotSizeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailschangedevent',
            name='pot_size_before',
            field=plant_tracker.models.pot_size_field.PotSizeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pot_size',
            field=plant_tracker.models.pot_size_field.PotSizeField(blank=True, null=True),
        ),
    ]
