# Generated by Django 5.2.8 on 2025-11-18 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0042_alter_detailschangedevent_pot_size_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailschangedevent',
            name='group_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_changed_after_events', to='plant_tracker.group'),
        ),
        migrations.AddField(
            model_name='detailschangedevent',
            name='group_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_changed_before_events', to='plant_tracker.group'),
        ),
    ]
