# Generated by Django 5.2.8 on 2025-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0043_detailschangedevent_group_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailschangedevent',
            name='archived_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailschangedevent',
            name='archived_before',
            field=models.BooleanField(default=False),
        ),
    ]
