# Generated by Django 5.2.8 on 2025-11-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_tracker', '0044_detailschangedevent_archived_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailschangedevent',
            name='uuid_after',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='detailschangedevent',
            name='uuid_before',
            field=models.UUIDField(null=True),
        ),
    ]
